import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Dispatch, SetStateAction, useState } from "react";
import { ImagesTab } from "@/components/images/ImagesTab";
import { PredictionsTab } from "@/components/predictions/PredictionsTab";
import { Typography } from "@mui/material";

export interface PredictionData {
  bbox: {
    x1: number;
    x2: number;
    y1: number;
    y2: number;
  };
  label: string;
  score: string;
}

export interface Prediction {
  title: string;
  description: string;
  time: Date;
  predictions: PredictionData[];
}

export interface MyImage {
  filename: string;
  size: number;
  time: Date;
  prediction: Prediction;
}

export interface ImageProps {
  images: MyImage[];
  setImages: Dispatch<SetStateAction<MyImage[]>>;
}

export default function Layout() {
  const [images, setImages] = useState<MyImage[]>([]);
  const [selectedTab, setSelectedTab] = useState<number>(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <nav className={styles.navbar}>
            <ul>
              <li onClick={() => setSelectedTab(0)}>Images</li>
              <li onClick={() => setSelectedTab(1)}>Predictions</li>
              <li>Encord</li>
            </ul>
          </nav>
          <div className={styles.wrapper}>
            <Typography variant="h4" className={styles.title}>
              Accurate Image predictions using AI
            </Typography>
            <div className={styles.center}>
              {selectedTab === 0 && (
                <ImagesTab images={images} setImages={setImages} />
              )}
              {selectedTab === 1 && (
                <PredictionsTab images={images} setImages={setImages} />
              )}
            </div>
            {/* <Home></Home> */}
          </div>
        </div>
      </main>
    </>
  );
}
